// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadFiletraceLsm returns the embedded CollectionSpec for filetraceLsm.
func loadFiletraceLsm() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FiletraceLsmBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load filetraceLsm: %w", err)
	}

	return spec, err
}

// loadFiletraceLsmObjects loads filetraceLsm and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*filetraceLsmObjects
//	*filetraceLsmPrograms
//	*filetraceLsmMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFiletraceLsmObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFiletraceLsm()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// filetraceLsmSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetraceLsmSpecs struct {
	filetraceLsmProgramSpecs
	filetraceLsmMapSpecs
	filetraceLsmVariableSpecs
}

// filetraceLsmProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetraceLsmProgramSpecs struct {
	LsmFileOpen           *ebpf.ProgramSpec `ebpf:"lsm_file_open"`
	TraceSchedProcessExec *ebpf.ProgramSpec `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit *ebpf.ProgramSpec `ebpf:"trace_sched_process_exit"`
}

// filetraceLsmMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetraceLsmMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// filetraceLsmVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetraceLsmVariableSpecs struct {
	TargetCgroupId *ebpf.VariableSpec `ebpf:"target_cgroup_id"`
}

// filetraceLsmObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFiletraceLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetraceLsmObjects struct {
	filetraceLsmPrograms
	filetraceLsmMaps
	filetraceLsmVariables
}

func (o *filetraceLsmObjects) Close() error {
	return _FiletraceLsmClose(
		&o.filetraceLsmPrograms,
		&o.filetraceLsmMaps,
	)
}

// filetraceLsmMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFiletraceLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetraceLsmMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *filetraceLsmMaps) Close() error {
	return _FiletraceLsmClose(
		m.Events,
	)
}

// filetraceLsmVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFiletraceLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetraceLsmVariables struct {
	TargetCgroupId *ebpf.Variable `ebpf:"target_cgroup_id"`
}

// filetraceLsmPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFiletraceLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetraceLsmPrograms struct {
	LsmFileOpen           *ebpf.Program `ebpf:"lsm_file_open"`
	TraceSchedProcessExec *ebpf.Program `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit *ebpf.Program `ebpf:"trace_sched_process_exit"`
}

func (p *filetraceLsmPrograms) Close() error {
	return _FiletraceLsmClose(
		p.LsmFileOpen,
		p.TraceSchedProcessExec,
		p.TraceSchedProcessExit,
	)
}

func _FiletraceLsmClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filetracelsm_bpfel.o
var _FiletraceLsmBytes []byte
